language: cpp

dist: trusty

compiler:
  - clang

script: rake run_tests

env:
  global:
    - SDB_VERSION=0.1.$TRAVIS_BUILD_NUMBER
    - SDB_BUILD=$TRAVIS_COMMIT
  matrix:
    - SDB_CONFIGURATION=debug
    - SDB_CONFIGURATION=release
